theme: jekyll-theme-minimal
title: Post 1
description: TÃ¸yenbadet
plugins:
  - jekyll-relative-links
  - jemoji 
relative_links:
  enabled: true
  collections: true
include:
  - README.md
github:
  is_project_page: false
